- hosts: ark_clients
  gather_facts: false

  vars:
    base_dir: "/opt/ark/instances/{{ instance_id }}"
    product_src: "{{ playbook_dir }}/../products/{{ product_id }}"
    product_dst: "{{ base_dir }}/product"
    shared_network_name: "ark_shared"

  tasks:
    - name: Asegurar que exista el directorio base
      ansible.builtin.file:
        path: "{{ base_dir }}"
        state: directory
        mode: "0755"

    - name: Asegurar que exista el directorio del producto
      ansible.builtin.file:
        path: "{{ product_dst }}"
        state: directory
        mode: "0755"

    - name: Copiar plantilla del producto al cliente
      ansible.posix.synchronize:
        src: "{{ product_src }}/"
        dest: "{{ product_dst }}/"
        recursive: true
        delete: true

    - name: Escribir .env de la instancia
      ansible.builtin.copy:
        dest: "{{ product_dst }}/.env"
        mode: "0644"
        content: |
          INSTANCE_ID={{ instance_id }}
          APP_ENV={{ env_name }}
          API_PORT=8080
          DB_PATH=/data/sara_memory.db
          CORS_ORIGINS=

    - name: Asegurar red docker compartida de instancias
      ansible.builtin.shell: |
        set -eu
        if docker network inspect "{{ shared_network_name }}" >/dev/null 2>&1; then
          exit 0
        fi

        for subnet in 172.31.250.0/24 172.31.251.0/24 172.31.252.0/24 10.250.10.0/24 10.250.11.0/24 10.251.10.0/24; do
          if docker network create --driver bridge --subnet "$subnet" "{{ shared_network_name }}" >/dev/null 2>&1; then
            echo "created {{ shared_network_name }} with subnet $subnet"
            exit 0
          fi
        done

        # Ultimo intento sin subnet explicita.
        docker network create --driver bridge "{{ shared_network_name }}" >/dev/null 2>&1 && exit 0

        echo "no fue posible crear la red {{ shared_network_name }} (sin subredes disponibles)"
        exit 1
      args:
        executable: /bin/sh

    - name: Ejecutar compose pull en cliente
      ansible.builtin.shell: |
        set -eu
        cd "{{ product_dst }}"
        docker compose --project-name "{{ instance_id }}" pull
      args:
        executable: /bin/sh

    - name: Ejecutar compose up en cliente
      ansible.builtin.shell: |
        set -eu
        cd "{{ product_dst }}"
        docker compose --project-name "{{ instance_id }}" up -d
      args:
        executable: /bin/sh
