- hosts: ark_clients
  gather_facts: false

  vars:
    base_dir: "/opt/ark/instances/{{ instance_id }}"
    product_src: "{{ playbook_dir }}/../products/{{ product_id }}"
    product_dst: "{{ base_dir }}/product"
    shared_network_name: "ark_shared"
    shared_network_subnet: "172.31.250.0/24"

  tasks:
    - name: Asegurar que exista el directorio base
      ansible.builtin.file:
        path: "{{ base_dir }}"
        state: directory
        mode: "0755"

    - name: Asegurar que exista el directorio del producto
      ansible.builtin.file:
        path: "{{ product_dst }}"
        state: directory
        mode: "0755"

    - name: Copiar plantilla del producto al cliente
      ansible.posix.synchronize:
        src: "{{ product_src }}/"
        dest: "{{ product_dst }}/"
        recursive: true
        delete: true

    - name: Escribir .env de la instancia
      ansible.builtin.copy:
        dest: "{{ product_dst }}/.env"
        mode: "0644"
        content: |
          INSTANCE_ID={{ instance_id }}
          APP_ENV={{ env_name }}
          API_PORT=8080
          DB_PATH=/data/sara_memory.db
          CORS_ORIGINS=

    - name: Asegurar red docker compartida de instancias
      ansible.builtin.shell: |
        set -eu
        docker network inspect "{{ shared_network_name }}" >/dev/null 2>&1 || docker network create --driver bridge --subnet "{{ shared_network_subnet }}" "{{ shared_network_name }}"
      args:
        executable: /bin/sh

    - name: Ejecutar compose pull en cliente
      ansible.builtin.shell: |
        set -eu
        cd "{{ product_dst }}"
        docker compose --project-name "{{ instance_id }}" pull
      args:
        executable: /bin/sh

    - name: Ejecutar compose up en cliente
      ansible.builtin.shell: |
        set -eu
        cd "{{ product_dst }}"
        docker compose --project-name "{{ instance_id }}" up -d
      args:
        executable: /bin/sh
